<?php

namespace TruongNX\Tutorial\Model\ResourceModel\FaqStore;

class Collection extends \Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection
{
    protected $_idFieldName = 'id';
    // protected $_eventPrefix = 'truongnx_tutorial_faq_collection';
    // protected $_eventObject = 'faq_collection';

    protected function _construct()
    {
        $this->_init(
            'TruongNX\Tutorial\Model\FAQStore',
            'TruongNX\Tutorial\Model\ResourceModel\FAQStore'
        );
    }

//    protected function _initSelect()
//    {
//        $this->addFilterToMap('id', 'faq_table.id');
//        return $this; // TODO: Change the autogenerated stub
//    }
}
